### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by bheadwhite** [chrispuppe/making-decisions#1]
https://github.com/chrispuppe/making-decisions/blob/d088bd63e1dc555ea0cd724eb3c54ea4128d5ebc/lab.js#L62

this works. if a variable is a boolean,  you can also use the variable as the condition ie: `rain` || `!rain`

https://github.com/chrispuppe/making-decisions/blob/d088bd63e1dc555ea0cd724eb3c54ea4128d5ebc/lab.js#L60-L65

nice!

https://github.com/chrispuppe/making-decisions/blob/d088bd63e1dc555ea0cd724eb3c54ea4128d5ebc/lab.js#L140-L142

`changeMyMind = !changeMyMind`

well done!

**Comment by chrispuppe** [comment]
Thanks for the help.
